version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ir-sam-app"
s3_bucket = "ir-sam-cli-managed-default-samclisourcebucket-19ok8vc9h95vh"
s3_prefix = "ir-sam-app"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
