version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ir-sam-app"
s3_bucket = "s3-ir-sam-app"
s3_prefix = "ir-sam-app"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
